---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami2
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami3
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami1
  name: whoami1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami1
  template:
    metadata:
      labels:
        app: whoami1
    spec:
      automountServiceAccountToken: false
      serviceAccountName: whoami1
      containers:
      - name: whoami
        image: containous/whoami
        ports:
          - containerPort: 80
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "sleep 999999999"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami2
  name: whoami2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami2
  template:
    metadata:
      labels:
        app: whoami2
    spec:
      automountServiceAccountToken: false
      serviceAccountName: whoami2
      containers:
      - name: whoami
        image: containous/whoami
        ports:
          - containerPort: 80
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "sleep 999999999"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami3
  name: whoami3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami3
  template:
    metadata:
      labels:
        app: whoami3
    spec:
      automountServiceAccountToken: false
      serviceAccountName: whoami3
      containers:
      - name: whoami
        image: containous/whoami
        ports:
          - containerPort: 80
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "sleep 999999999"]
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: default
  name: whoami2-whoami1-auth
spec:
  server:
    name: whoami1
  # The voting service only allows requests from the web service.
  client:
    meshTLS:
      serviceAccounts:
        - name: whoami2

