---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: mydemo1
  name: whoami4-whoami1-auth
  labels:
    app.kubernetes.io/part-of: whoami
    app.kubernetes.io/name: whoami4-whoami1
spec:
  # the Server whoami1 can be contacted by Pods running with whoami2 ServiceAccount
  server:
    name: whoami1-server
  client:
    meshTLS:
      serviceAccounts:
        - name: whoami4
          namespace: mydemo2

