---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami2
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami3
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami1
  name: whoami1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami1
  template:
    metadata:
      labels:
        app: whoami1
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
        resources: {}
      serviceAccount: whoami1
      serviceAccountName: whoami1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami2
  name: whoami2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami2
  template:
    metadata:
      labels:
        app: whoami2
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
      serviceAccount: whoami2
      serviceAccountName: whoami2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami3
  name: whoami3
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami3
  template:
    metadata:
      labels:
        app: whoami3
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
      serviceAccount: whoami3
      serviceAccountName: whoami3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami1
  name: whoami1
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami2
  name: whoami2
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami3
  name: whoami3
  namespace: default
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami3
  sessionAffinity: None
  type: ClusterIP