---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami4
  namespace: mydemo2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami5
  namespace: mydemo2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami6
  namespace: mydemo2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami4
  name: whoami4
  namespace: mydemo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami4
  template:
    metadata:
      labels:
        app: whoami4
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
        resources: {}
      serviceAccount: whoami4
      serviceAccountName: whoami4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami5
  name: whoami5
  namespace: mydemo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami5
  template:
    metadata:
      labels:
        app: whoami5
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
      serviceAccount: whoami5
      serviceAccountName: whoami5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami6
  name: whoami6
  namespace: mydemo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami6
  template:
    metadata:
      labels:
        app: whoami6
    spec:
      automountServiceAccountToken: false
      containers:
      - image: containous/whoami
        imagePullPolicy: Always
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
      - args:
        - -c
        - sleep 999999999
        command:
        - /bin/bash
        image: nicolaka/netshoot
        imagePullPolicy: Always
        name: netshoot
      serviceAccount: whoami6
      serviceAccountName: whoami6
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami4
  name: whoami4
  namespace: mydemo2
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami4
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami5
  name: whoami5
  namespace: mydemo2
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami5
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: whoami6
  name: whoami6
  namespace: mydemo2
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami6
  sessionAffinity: None
  type: ClusterIP