---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: mydemo2
  name: whoami4-server
  labels:
    app: whoami4
spec:
  podSelector:
    matchLabels:
      app: whoami4
  port: 80
  proxyProtocol: HTTP/1